# hello_jenkins.py
"""
Simple Python script to demonstrate Jenkins automation
and integration with Git.
"""

import os
from datetime import datetime

def main():
    # Print a greeting
    print("Hello Jenkins!")

    # Print current timestamp
    now = datetime.now()
    print(f"Current time: {now}")

    # Create a file dynamically
    filename = "jenkins_output.txt"
    with open(filename, "w") as f:
        f.write(f"Build executed at: {now}\n")
        f.write("This file is generated by Jenkins using Python.\n")

    print(f"{filename} created successfully!")

if __name__ == "__main__":
    main()
